In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [8]:
# First Classifier - LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

C:\Users\S537849\Anaconda3\envs\ML\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [9]:
# Second Classifier - SVM
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.987037037037037

In [10]:
# Third Classifier - RandomForest
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.975925925925926

In [11]:
# K Fold
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3) # number of folds
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


left side training folds, right side testing folds. 3 fold iterations as specified above. Once test fold is used notice it is moved to training fold and vice versa for training folds.

In [13]:
# Create function that will pass each model classifier and return model score
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [14]:
get_score(LogisticRegression(), x_train, x_test, y_train, y_test)

C:\Users\S537849\Anaconda3\envs\ML\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [15]:
get_score(SVC(), x_train, x_test, y_train, y_test)

0.987037037037037

In [16]:
get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test)

0.9685185185185186

In [17]:
# Using K folds for digits example
from  sklearn.model_selection import StratifiedKFold #divides each classification categories in uniform way when separating

In [18]:
folds = StratifiedKFold(n_splits = 3)

In [34]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

C:\Users\S537849\Anaconda3\envs\ML\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\S537849\Anaconda3\envs\ML\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

In [25]:
# above cell for loop can be done with less code using cross val score
from sklearn.model_selection import cross_val_score

In [41]:
cross_val_score(LogisticRegression(), digits.data, digits.target, cv=folds)

C:\Users\S537849\Anaconda3\envs\ML\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\S537849\Anaconda3\envs\ML\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

array([0.92153589, 0.94156928, 0.91652755])

In [42]:
cross_val_score(SVC(), digits.data, digits.target, cv=folds)

array([0.96494157, 0.97996661, 0.96494157])

In [43]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=folds)

array([0.93656093, 0.95325543, 0.92821369])

In [35]:
scores_lr

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [36]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [37]:
scores_rf

[0.9282136894824707, 0.9515859766277128, 0.9332220367278798]

In [45]:
# Average each of the three scores to determine best model
scores = []
scores.append(scores_lr)
scores.append(scores_svm)
scores.append(scores_rf)
scores

[[0.9215358931552587, 0.9415692821368948, 0.9165275459098498],
 [0.9649415692821369, 0.9799666110183639, 0.9649415692821369],
 [0.9282136894824707, 0.9515859766277128, 0.9332220367278798]]

In [46]:
avg_score = np.mean(scores)
print(avg_score)

0.9447226859580784
